// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EncryptText(arg1:string):Promise<void>;

export function GetMsgList():Promise<Array<main.Message>>;

export function Greet(arg1:string):Promise<string>;

export function ScanNewMsg():Promise<Array<string>>;

export function SetNickName(arg1:string):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;
