// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EncryptText(arg1) {
  return window['go']['main']['App']['EncryptText'](arg1);
}

export function GetMsgList() {
  return window['go']['main']['App']['GetMsgList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ScanNewMsg() {
  return window['go']['main']['App']['ScanNewMsg']();
}

export function SetNickName(arg1) {
  return window['go']['main']['App']['SetNickName'](arg1);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}
